# inventory/hosts.yml - Inventario de servidores para el laboratorio

all:
  children:
    webservers:
      hosts:
        # SERVIDORES WEB - Reemplazar con tus IPs reales
        web1:
          ansible_host: 52.188.81.6 
          ansible_user: amalaver           
          server_id: 1                   
          nginx_worker_processes: 2      
          
        web2:
          ansible_host: 135.237.121.243
          ansible_user: amalaver
          server_id: 2
          nginx_worker_processes: 2
          
      vars:
        # VARIABLES ESPECÍFICAS DE WEBSERVERS
        http_port: 80                    
        https_port: 443                  
        nginx_user: www-data             
        document_root: /var/www/html     
        
    # Grupo para testing (opcional)
    testing:
      hosts:
        web1:                            
        
  vars:
    # VARIABLES GLOBALES (todos los hosts)
    environment_name: "laboratorio"      
    admin_email: "admin@empresa.com"     
    timezone: "America/Lima"             

