---
# playbooks/install-nginx.yml - Instalación de Nginx y dependencias

# TAREAS DE INSTALACIÓN
- name: "Debug: Verificar variables cargadas"
  debug:
    msg: |
      Variables del sistema:
      - system_packages: {{ system_packages | default('NO DEFINIDO') }}
      - environment_name: {{ environment_name | default('NO DEFINIDO') }}
      - timezone: {{ timezone | default('NO DEFINIDO') }}
  tags: ['debug']

- name: "Sistema: Configurar timezone"
  timezone:
    name: "{{ ntp_timezone }}"
  when: ntp_timezone is defined
  tags: ['install', 'system']

- name: "Sistema: Instalar paquetes del sistema"
  package:
    name: "{{ system_packages | default(['curl', 'wget', 'unzip', 'vim', 'htop', 'tree']) }}"
    state: present
  tags: ['install', 'packages']

- name: "Sistema: Crear usuario administrativo"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    state: present
  loop: "{{ admin_users }}"
  when: admin_users is defined
  tags: ['install', 'users']

- name: "Nginx: Instalar nginx"
  package:
    name: nginx
    state: present
  notify:
    - enable nginx
  tags: ['install', 'nginx']

- name: "Nginx: Verificar instalación"
  command: nginx -v
  register: nginx_version_check
  changed_when: false
  tags: ['install', 'verify']

- name: "Nginx: Mostrar versión instalada"
  debug:
    msg: "Nginx instalado: {{ nginx_version_check.stderr }}"
  tags: ['install', 'verify']

- name: "Sistema: Configurar logrotate básico"
  package:
    name: logrotate
    state: present
  tags: ['install', 'logrotate']

- name: "Red: Configurar UFW si está habilitado"
  package:
    name: ufw
    state: present
  when: firewall_enabled | default(false)
  tags: ['install', 'firewall']

- name: "Verificación: Estado del servicio nginx"
  service:
    name: nginx
    state: started
    enabled: yes
  tags: ['install', 'service']

- name: "Verificación: Comprobar que nginx está escuchando"
  wait_for:
    port: 80
    host: "{{ ansible_default_ipv4.address }}"
    delay: 5
    timeout: 30
  tags: ['install', 'verify']

- name: "Info: Mostrar resumen de instalación"
  debug:
    msg: |
      =====================================
      INSTALACIÓN COMPLETADA
      =====================================
      Host: {{ ansible_hostname }}
      Nginx Version: {{ nginx_version_check.stderr }}
      Estado: Instalado y funcionando
      Puerto: 80 activo
      Próximo paso: Configuración
      =====================================
  tags: ['install', 'info']

